const popup = document.getElementById("project-popup");
const popupContent = document.getElementById("popup-inner-content");
const closeBtn = document.getElementById("popup-close");
const scrollProgress = document.getElementById("scroll-progress");
const navMenuButton = document.querySelector(".nav-menu-button");
const navList = document.getElementById("nav-links");

const projectsData = {
  "blade-of-the-dawn": `
    <img class="project-hero-image" onerror="this.hidden=true" src="images/blade-hero.jpg" alt="Blade of the Dawn Japanese-inspired game environment" />
    <h2 id="popup-title">Blade of the Dawn</h2>
    <div class="popup-meta"><span>Third-Person Game</span><span>Unity</span><span>C#</span><span>Gameplay Systems</span><span>Enemy AI</span><span>Individual Project</span></div>
    <section class="project-quick-facts" aria-labelledby="blade-facts-title"><h3 id="blade-facts-title">Quick Facts</h3><dl class="quick-facts-grid">
      <div><dt>University</dt><dd>Darmstadt University of Applied Sciences (h_da), Germany</dd></div><div><dt>Faculty</dt><dd>Faculty of Media</dd></div>
      <div><dt>Study Programme</dt><dd>Bachelor of Arts (B.A.) &ndash; Expanded Realities</dd></div><div><dt>Course</dt><dd>ER-T2 &ndash; Technology in Expanded Realities</dd></div>
      <div><dt>Semester</dt><dd>Summer Semester 2024</dd></div><div><dt>Project Type</dt><dd>Individual Final Project</dd></div><div><dt>Engine</dt><dd>Unity 2022.3 LTS</dd></div><div><dt>Language</dt><dd>C#</dd></div>
    </dl></section>
    <h3>Overview</h3><p><strong>Blade of the Dawn</strong> is a third-person 3D action-adventure game developed as the individual final project for ER-T2. Players explore a Japanese-inspired village and castle, interact with NPCs, collect items, fight enemy guards, and progress towards a final boss. Multiple gameplay systems form one complete playable experience.</p>
    <h3>Video</h3><!-- TODO: add the Gameplay Walkthrough when the YouTube URL is available. --><p class="project-media-note">Gameplay walkthrough coming soon.</p>
    <h3>Gallery</h3><div class="popup-image-grid"><img onerror="this.hidden=true" src="images/blade-01.jpg" alt="Blade of the Dawn third-person gameplay" /><img onerror="this.hidden=true" src="images/blade-02.jpg" alt="Exploration in Blade of the Dawn" /><img onerror="this.hidden=true" src="images/blade-03.jpg" alt="Boss encounter in Blade of the Dawn" /><img onerror="this.hidden=true" src="images/blade-04.jpg" alt="Blade of the Dawn gameplay UI and environment" /></div>
    <h3>Technical Highlights</h3><p>A third-person character controller supports a three-stage melee combo through Animator integration and trigger-based hit detection. NavMesh enemies use idle, patrol, chase, attack, damage, and death states. Collectible and health pickups use Scriptable Objects and Unity Events for communication across combat, UI, audio, and three connected scenes.</p>
    <h3>My Contribution</h3><p>This was an individual project. I created the game concept and gameplay structure and implemented the complete experience in Unity and C#, including the player controller, combat, enemy AI, interactions, collectibles, scene progression, UI, animation and audio integration, testing, and refinement.</p>
    <h3>Challenges</h3><p>The main challenges were integrating independent systems into one stable experience, synchronising animation with hit detection and combat timing, coordinating AI states with NavMesh navigation, and keeping communication between UI, collectibles, combat, and scenes reusable.</p>
    <h3>What I Learned</h3><p>The project strengthened my Unity gameplay programming, component-based architecture, object-oriented programming, NavMesh, Animator state machines, event-driven systems, Scriptable Objects, scene management, and UI and audio integration skills while completing a full game rather than an isolated prototype.</p>
    <h3>Project Links</h3><div class="project-external-links"><a href="https://github.com/antonelamatanovich/Blade-Of-The-Dawn" target="_blank" rel="noopener" class="project-external-link">github &nearr;</a><!-- TODO: add Gameplay Walkthrough URL. --></div>  `,

  "retro-snake": `
    <h2 id="popup-title">Retro Snake</h2>
    <div class="popup-meta"><span>Desktop Game</span><span>Processing</span><span>Java</span><span>Game Programming</span><span>Individual Final Project</span><span>University Project</span></div>
    <section class="project-quick-facts" aria-labelledby="retro-snake-facts-title"><h3 id="retro-snake-facts-title">Quick Facts</h3><dl class="quick-facts-grid">
      <div><dt>University</dt><dd>Darmstadt University of Applied Sciences (h_da), Germany</dd></div><div><dt>Faculty</dt><dd>Faculty of Media</dd></div><div><dt>Study Programme</dt><dd>Bachelor of Arts (B.A.) &ndash; Expanded Realities</dd></div><div><dt>Course</dt><dd>ER-T1 &ndash; Fundamentals of Technology in Expanded Realities</dd></div><div><dt>Semester</dt><dd>Winter Semester 2023/2024</dd></div><div><dt>Project Type</dt><dd>Individual Final Project</dd></div><div><dt>Format</dt><dd>Desktop Arcade Game</dd></div><div><dt>Framework</dt><dd>Processing &ndash; Java Mode</dd></div><div><dt>Language</dt><dd>Java / Processing</dd></div>
    </dl></section>
    <h3>Overview</h3><p><strong>Retro Snake</strong> is a desktop recreation of the classic Snake arcade game, developed with Processing in Java mode as the final project for ER-T1 &ndash; Fundamentals of Technology in Expanded Realities.</p><p>The project combines grid-based movement, collectible spawning, scoring, collision detection, screen navigation and replay functionality within a monochrome pixel-art presentation inspired by early arcade games. As my first complete programming project, it established a foundation for my later work in Unity, XR and interactive application development.</p>
    <h3>Gameplay Preview</h3><figure class="popup-media popup-media--contained"><img src="images/retro snake.gif" alt="Retro Snake gameplay showing the snake moving across the grid, collecting food and increasing the score" class="popup-image popup-image--contained" /><figcaption>Core gameplay with grid-based movement, food collection, snake growth and score tracking.</figcaption></figure>
    <h3>Gameplay</h3><p>The player guides a snake across a grid-based playfield, collecting food to grow while avoiding the window boundaries and the snake&rsquo;s own body. Each collected item adds one body segment, awards five points and generates new food at a random grid-aligned position. A collision ends the run and opens the Game Over screen, where the player can retry or return to the main menu.</p>
    <h3>Technical Highlights</h3><ul><li><strong>Real-Time Game Loop:</strong> Processing&rsquo;s <code>setup()</code> and <code>draw()</code> lifecycle provides continuous updates and rendering with keyboard-driven movement.</li><li><strong>Grid-Based Movement:</strong> Fixed 20-pixel steps support four directions while preventing immediate reversal.</li><li><strong>Snake Body Representation:</strong> Coordinate arrays let segments follow previous head positions and grow after collection.</li><li><strong>Food and Scoring:</strong> Random grid-aligned food, pickup detection, five points per item and respawning.</li><li><strong>Collision Detection:</strong> Wall and self-collisions transition to Game Over.</li><li><strong>Screen-State Management:</strong> A shared state variable creates a lightweight finite-state flow across Main Menu, Controls, Rules, Gameplay and Game Over.</li><li><strong>Replay and Reset:</strong> Restarting resets position, length, direction, food and score.</li></ul>
    <h3>Interface &amp; Game States</h3><p>Beyond the core gameplay loop, the application includes a complete menu, onboarding and game-over flow built within the same Processing sketch.</p>
    <div class="popup-gallery popup-gallery--four">
      <figure><img src="images/start screen.png" loading="lazy" alt="Retro Snake main menu with Play, Controls and Rules buttons beneath a rotating pixel spiral" /><figcaption>Main menu with animated visual branding and mouse-based navigation.</figcaption></figure>
      <figure><img src="images/help screen.png" loading="lazy" alt="Retro Snake controls screen showing the arrow keys used to control the snake" /><figcaption>Controls screen introducing the four-direction keyboard input.</figcaption></figure>
      <figure><img src="images/rules screen.png" loading="lazy" alt="Retro Snake rules screen explaining food collection, growth and wall or self-collision" /><figcaption>Rules screen explaining the objective and the main loss conditions.</figcaption></figure>
      <figure><img src="images/game over.png" loading="lazy" alt="Retro Snake Game Over screen with a pixel-art skull, Retry button and Back navigation" /><figcaption>Game-over state providing retry and back-navigation options after a collision.</figcaption></figure>
    </div>
    <h3>My Contribution</h3><p>This was an individual project.</p><ul><li>I designed the complete game structure and interaction flow.</li><li>I programmed the gameplay in Processing using Java mode.</li><li>I implemented grid-based movement, snake growth, food spawning, wall and self-collision detection, and scoring.</li><li>I developed the menu, instructions, rules and Game Over screens.</li><li>I implemented replay and reset functionality.</li><li>I structured the project across responsibility-based Processing tabs.</li><li>I integrated the monochrome visual assets, font and interface presentation without claiming authorship of third-party assets.</li><li>I tested and refined the complete desktop application.</li></ul>
    <h3>Challenges</h3><p>As an early programming project, the meaningful challenges included representing a growing moving body with coordinate arrays, ensuring each segment followed the correct previous position, preventing immediate reversal, and detecting wall and self-collisions reliably. I also had to reset every gameplay variable on restart and manage several application screens without a framework, combining gameplay, menus and replay while learning how real-time update and rendering loops work.</p>
    <h3>What I Learned</h3><p>I learned how Processing&rsquo;s <code>setup()</code> and <code>draw()</code> lifecycle supports real-time keyboard and mouse input, and gained experience with classes, objects, arrays and responsibility-based tabs. Building the complete application developed my understanding of grid movement, collision detection, scoring, application states, menu and Game Over flows, reusable reset logic, and loading fonts and raster images. It established the programming foundation for my later Unity, XR and interactive development work.</p>
    <h3>Controls</h3><dl class="project-controls"><div><dt>Right Arrow</dt><dd>Move right</dd></div><div><dt>Down Arrow</dt><dd>Move down</dd></div><div><dt>Left Arrow</dt><dd>Move left</dd></div><div><dt>Up Arrow</dt><dd>Move up</dd></div><div><dt>Mouse</dt><dd>Play, Controls, Rules, Retry, Back and Main Menu buttons</dd></div></dl><p>The snake cannot immediately reverse into the opposite direction.</p>
    <h3>Future Improvements</h3><ul><li>Persistent high-score system</li><li>Dynamic speed and difficulty progression</li><li>Preventing food from spawning on the snake</li><li>Pause functionality and WASD controls</li><li>Keyboard-accessible menus and improved button feedback</li><li>Dynamic snake-body storage</li><li>Replacing remaining third-party visual assets with original or clearly licensed artwork</li></ul>
    <h3>Project Links</h3><div class="project-external-links"><a href="https://github.com/antonelamatanovich/Retro-Snake" target="_blank" rel="noopener" class="project-external-link">GitHub Repository &nearr;</a></div>
  `,
  "discovering-barite": `
    <img class="project-hero-image project-hero-image--contain" src="images/third person view.png" alt="Visitor using the Discovering Barite mobile AR experience at the Spatschlucht" />
    <h2 id="popup-title">Discovering Barite</h2>
    <div class="popup-meta"><span>Mobile Augmented Reality</span><span>Unity</span><span>Vuforia</span><span>Image Tracking</span><span>Spatial Interaction</span><span>University Team Project</span></div>

    <section class="project-quick-facts" aria-labelledby="barite-facts-title"><h3 id="barite-facts-title">Quick Facts</h3><dl class="quick-facts-grid">
      <div><dt>University</dt><dd>Darmstadt University of Applied Sciences (h_da), Germany</dd></div><div><dt>Faculty</dt><dd>Faculty of Media</dd></div><div><dt>Study Programme</dt><dd>Bachelor of Arts (B.A.) &ndash; Expanded Realities</dd></div><div><dt>Course</dt><dd>Project 5</dd></div><div><dt>Semester</dt><dd>Winter Semester 2025/26</dd></div><div><dt>Project Type</dt><dd>University Team Project</dd></div><div><dt>Project Partner</dt><dd>Geo-Naturpark Bergstra&szlig;e-Odenwald</dd></div><div><dt>Location</dt><dd>Spatschlucht near Schriesheim, Germany</dd></div><div><dt>Format</dt><dd>Place-Based Mobile AR Experience</dd></div><div><dt>Engine</dt><dd>Unity 6.2</dd></div><div><dt>Tracking</dt><dd>Vuforia 11.4.4</dd></div><div><dt>Render Pipeline</dt><dd>Universal Render Pipeline (URP)</dd></div>
    </dl></section>

    <h3>Overview</h3>
    <p><strong>Discovering Barite</strong> is a place-based mobile augmented reality experience developed during Project 5 at Darmstadt University of Applied Sciences in collaboration with Geo-Naturpark Bergstra&szlig;e-Odenwald.</p>
    <p>Designed for the Spatschlucht near Schriesheim, the project uses the real gorge as the physical context for exploring geological processes and the site&rsquo;s history of barite mining.</p>
    <p>Through digital storytelling, spatial interaction and geological interpretation, visitors reconstruct and look inside structures no longer directly visible. The central concept is to reveal the hidden structure of the landscape, including mineral layers and barite veins shaped by geology and mining history.</p>

    <h3>Experience Journey</h3>
    <div class="experience-journey">
      <section class="experience-stage"><p class="experience-stage-label">Stage 1</p><h4>Arriving at the Spatschlucht</h4><p>Visitors arrive at the real geological site, where the natural gorge provides the physical context. A mobile device becomes a viewing tool for hidden information while the experience introduces the location and its history of barite extraction.</p><div class="popup-image-grid"><img src="images/location.png" alt="Information sign marking the Spatschlucht geological site" /><img src="images/gorge.jpg" alt="Natural rock walls and pathway inside the Spatschlucht" /></div></section>
      <section class="experience-stage"><p class="experience-stage-label">Stage 2</p><h4>Aligning the digital reconstruction</h4><p>Image-based tracking aligns a readable virtual rock face with the physical gorge. This replaced an earlier setup that placed content between two opposing tracked walls, giving visitors a clearer spatial reference and a more stable, understandable phone-based view.</p><div class="popup-image-grid popup-image-grid--single"><img class="gallery-image--contain" src="images/first person view.png" alt="First-person phone view of the augmented rock structure" /></div></section>
      <section class="experience-stage"><p class="experience-stage-label">Stage 3</p><h4>Revealing the hidden layers</h4><p>A guided UI slider moves a slicing plane through the virtual rock. As the adapted cross-section shader hides the outer geometry, internal mineral layers and barite veins appear step by step, helping visitors explore how the structure formed and how mining changed the landscape.</p></section>
    </div>

    <h3>Video</h3><div class="video-container"><iframe src="https://www.youtube.com/embed/iN2uR1dm6d4" title="Discovering Barite project trailer" allowfullscreen></iframe></div>

    <h3>Gallery</h3><div class="popup-image-grid">
      <img src="images/location.png" alt="Information sign and surrounding landscape at the Spatschlucht" /><img src="images/gorge.jpg" alt="Rock walls and forest floor inside the Spatschlucht" /><img class="gallery-image--contain" src="images/first person view.png" alt="First-person mobile AR view with navigation and geological content" /><img class="gallery-image--contain" src="images/third person view.png" alt="Visitor viewing the augmented reconstruction through a mobile phone" /><img src="images/third person.jpg" alt="On-site third-person view of the Discovering Barite experience" />
    </div>

    <h3>Technical Highlights</h3>
    <p>The final mobile AR implementation uses Unity 6.2, Vuforia 11.4.4 and the Universal Render Pipeline. Image-based tracking aligns a 3D reconstruction of the gorge with the site, while UI events connect the guided experience logic to the geological cross-section interaction.</p>
    <p>A cross-section shader found during development was adapted and customised for geological visualisation. Its clipping plane hides outer virtual geometry, and a UI slider moves the plane through the model so visitors can reveal barite veins in real time.</p>
    <p>Because terrain, weather and accessibility made repeated location testing difficult, the team created a 1:1 spatial simulation based on a 3D scan of the gorge. This repeatable indoor environment supported faster iteration before on-site validation, alongside mobile performance optimisation. The project initially used Unity 2022.3, AR Foundation and ARCore before moving to the final Unity 6.2, Vuforia and URP setup.</p>

    <h3>My Contribution</h3><ul><li>I developed and tested the image-tracking system.</li><li>I designed and optimised the mobile UI layout.</li><li>I integrated game events and interaction logic with UI elements.</li><li>I contributed programming work across the mobile AR experience.</li><li>I supported project management and team coordination.</li><li>I took part in prototype testing and on-site validation.</li><li>I helped refine the interaction from a technically driven setup into a clearer user journey.</li></ul>

    <h3>Challenges</h3>
    <ul><li><strong>Tracking and alignment:</strong> Limited connectivity and unreliable GPS precision led the team towards image-based tracking, with careful alignment between the reconstruction and physical gorge.</li><li><strong>Limited on-site testing:</strong> Terrain, weather and travel constraints led to the repeatable indoor 3D simulation.</li><li><strong>Mobile performance:</strong> Geometry, rendering and cross-section effects needed to remain usable on a mobile device.</li><li><strong>Render pipeline transition:</strong> Moving from the Standard Render Pipeline to URP required existing materials and systems to be adjusted.</li><li><strong>Project recovery:</strong> A late-stage project-file failure required the application to be rebuilt from a stable foundation under significant time pressure.</li></ul>

    <h3>What I Learned</h3>
    <p>I developed experience in mobile AR interaction design, Vuforia tracking, spatial alignment and calibration, real-location interaction design, shader adaptation, UI event integration, Unity and URP workflows, and mobile optimisation. The project also strengthened my iterative indoor and on-site testing, external-partner collaboration, coordination and recovery under time pressure, and ability to translate complex geological content into accessible spatial interaction.</p>

    <h3>Team</h3><p>Antonela Matanovi&#263; &middot; Jacopo Perilli &middot; Karam Al Sawaftah</p>

    <h3>Project Links</h3><div class="project-external-links"><a href="https://www.youtube.com/watch?v=iN2uR1dm6d4" target="_blank" rel="noopener" class="project-external-link">Watch Project Video &nearr;</a><a href="https://geo-naturpark.net" target="_blank" rel="noopener" class="project-external-link" aria-label="Project Partner: Geo-Naturpark Bergstraße-Odenwald">Geo-Naturpark Bergstra&szlig;e-Odenwald &nearr;</a></div>  `,

  "animal-garden": `
    <h2 id="popup-title">Animal Garden</h2><div class="popup-meta"><span>Interactive Installation</span><span>Unity</span><span>C#</span><span>Hardware Build</span><span>Exhibition</span><span>Work Project</span></div>
    <section class="project-quick-facts" aria-labelledby="animal-facts-title"><h3 id="animal-facts-title">Quick Facts</h3><dl class="quick-facts-grid"><div><dt>Company</dt><dd>videoreality GmbH</dd></div><div><dt>Role</dt><dd>XR Development Intern</dd></div><div><dt>Internship Period</dt><dd>17 February &ndash; 27 June 2025</dd></div><div><dt>Academic Context</dt><dd>Fourth-Semester Industrial Placement</dd></div><div><dt>Exhibition</dt><dd>TimeLeapVR Artworld &ndash; Mona Lisas Geheimnis</dd></div><div><dt>Exhibition Room</dt><dd>Boschs Traumwelt</dd></div><div><dt>Location</dt><dd>The Squaire, Frankfurt Airport</dd></div><div><dt>Project Type</dt><dd>Participatory Interactive Installation</dd></div><div><dt>Engine</dt><dd>Unity</dd></div><div><dt>Programming</dt><dd>C#</dd></div><div><dt>Computer Vision</dt><dd>OpenCV Integration</dd></div><div><dt>Art Pipeline</dt><dd>Adobe Photoshop and Unity 2D Animation</dd></div><div><dt>Format</dt><dd>Physical Scanner and Projected Digital Environment</dd></div></dl></section>
    <h3>Overview</h3><p><strong>Animal Garden</strong> is a participatory installation developed during my industrial placement at videoreality GmbH for the family-friendly public exhibition <em>TimeLeapVR Artworld &ndash; Mona Lisas Geheimnis</em>. Visitors colour one of five printed animal templates, insert the drawing into a custom scanner station and see their artwork become an animated creature within a projected Unity environment inspired by Hieronymus Bosch&rsquo;s <em>The Garden of Earthly Delights</em>.</p><p>A top-mounted camera captures the page, while an OpenCV-based workflow identifies the animal and aligns the drawing through its QR code and corner markers. Unity maps the processed artwork onto the matching rigged sprite, then spawns it into the garden with an appropriate walking, swimming, flying or idle behaviour. Animal Garden and the related VR experience <em>DelightfulGardenVR</em> share the same Bosch-inspired conceptual and aesthetic world.</p>
    <figure class="popup-media popup-media--contained"><img src="images/visitor 1.JPG" alt="Visitors using the Animal Garden drawing table while the Bosch-inspired digital environment is projected behind the installation" /><figcaption>Animal Garden in use during the public TimeLeapVR Artworld exhibition.</figcaption></figure>
    <h3>How It Works</h3><div class="experience-journey"><section class="experience-stage"><p class="experience-stage-label">Step 1</p><h4>Colour</h4><p>Visitors select one of five print sheets and colour the outlined creature. Each standardised sheet contains an animal outline, QR identification and four corner markers for alignment.</p></section><section class="experience-stage"><p class="experience-stage-label">Step 2</p><h4>Scan</h4><p>The completed sheet is inserted into the custom station, where a top-mounted camera captures the drawing at a controlled distance.</p></section><section class="experience-stage"><p class="experience-stage-label">Step 3</p><h4>Process</h4><p>The OpenCV pipeline identifies the animal type, detects the marker points, aligns the capture and prepares the artwork for texture mapping. Technical Director Linus Steffens developed the core reading functionality and standardised print sheets.</p></section><section class="experience-stage"><p class="experience-stage-label">Step 4</p><h4>Animate</h4><p>Unity maps the captured texture onto the corresponding rigged and animated 2D sprite.</p></section><section class="experience-stage"><p class="experience-stage-label">Step 5</p><h4>Enter the Garden</h4><p>The creature enters the projected Bosch-inspired scene and follows behaviour suited to its character, including walking, swimming, flying or idling.</p></section></div>
    <h3>From Drawing to Animated Creature</h3><p>The installation connects a physical drawing activity with a real-time digital pipeline. Each coloured sheet is captured, identified and mapped onto a rigged animal before entering the projected scene.</p><div class="popup-gallery popup-gallery--two"><figure><img src="images/cropping animals.png" loading="lazy" alt="Adobe Photoshop workspace isolating a bird-like creature from Bosch&rsquo;s painting" /><figcaption>Animal and environmental elements were isolated in Photoshop for preparation and adaptation.</figcaption></figure><figure><img src="images/before and after cleanup.png" loading="lazy" alt="Side-by-side comparison of a cleaned Bosch landscape asset and its original painting excerpt" /><figcaption>Visual cleanup removed unrelated figures while preserving the source painting&rsquo;s composition and texture.</figcaption></figure><figure><img src="images/animating animals.png" loading="lazy" alt="Unity 2D Animation workspace showing a rigged long-bodied creature and its bone controls" /><figcaption>Rigged 2D sprites were animated in Unity and prepared for dynamically scanned textures.</figcaption></figure><figure><img src="images/finished scene.png" loading="lazy" alt="Completed Bosch-inspired Unity garden scene with layered landscape elements and animal characters" /><figcaption>The completed scene combines animated creatures, layered parallax backgrounds and visitor-created textures.</figcaption></figure></div>
    <h3>Technical Highlights</h3><ul><li><strong>Capture and mapping:</strong> Physical camera input connects Linus Steffens&rsquo; OpenCV, QR and corner-marker recognition workflow to dynamic texture mapping in Unity.</li><li><strong>Instance management:</strong> An early remove-oldest approach was expanded into active-animal tracking and recycling to manage multiple continuously spawned creatures.</li><li><strong>Movement and behaviour:</strong> Spline- and waypoint-based paths support walking, swimming and flying, with basic behaviour-state logic controlling idle and movement states.</li><li><strong>2D production:</strong> Photoshop asset preparation, Unity 2D rigging, sprite animation and billboarded sprites preserve visitor artwork while supporting deformation and motion.</li><li><strong>Environment:</strong> Layered parallax composition, shaders and assets adapted from Bosch&rsquo;s painting create depth across the projected scene.</li><li><strong>Delivery:</strong> Git and GitHub supported collaboration, while physical camera integration, projection calibration, hardware prototyping, builds and exhibition testing connected software to the installed experience.</li></ul>    <h3>Animal Character Set</h3><p>Five creatures were selected from Bosch&rsquo;s imagery according to silhouette, recognisability and suitability for sprite rigging and animation. Four standalone production sprites are available in the portfolio media set.</p><div class="popup-gallery popup-gallery--four popup-gallery--characters"><figure><img src="images/weirdbird.png" loading="lazy" alt="Transparent bird-like Animal Garden sprite with a dark body and extended legs" /><figcaption>A bird-like creature prepared for rigging and animated movement.</figcaption></figure><figure><img src="images/handweasel.png" loading="lazy" alt="Transparent long-bodied Animal Garden creature sprite with raised limbs" /><figcaption>A long-bodied creature selected for its distinctive silhouette and movement potential.</figcaption></figure><figure><img src="images/hedgehog.png" loading="lazy" alt="Transparent blue hedgehog-like Animal Garden creature sprite with long spines" /><figcaption>A hedgehog-like creature whose clear outline supports recognition after texture mapping.</figcaption></figure><figure><img src="images/orangefish.png" loading="lazy" alt="Transparent orange fish-like Animal Garden creature sprite" /><figcaption>A fish-like creature prepared for swimming animation within the projected garden.</figcaption></figure></div>
    <h3>Building the Scanner Station</h3><p>The scanner was developed as a custom exhibition object combining a wooden structural frame, top-mounted camera, internal computer space, paper slot and matte-black visitor-facing enclosure. Design and construction were collaborative, primarily with Riccardo Liguori and under Michael G&ouml;dde&rsquo;s supervision.</p><div class="popup-gallery popup-gallery--two"><figure><img src="images/prototype.jpg" loading="lazy" alt="Full-scale duct-tape scanner prototype used to test Animal Garden dimensions and proportions" /><figcaption>An early full-scale prototype validated the scanner&rsquo;s proportions and planned component placement.</figcaption></figure><figure><img src="images/building progress (1).jpg" loading="lazy" alt="Initial wooden skeleton of the Animal Garden scanner during construction" /><figcaption>The wooden skeleton established the station&rsquo;s structural dimensions and internal volume.</figcaption></figure><figure><img src="images/building progress (3).jpg" loading="lazy" alt="Animal Garden scanner frame with supports for the camera platform, paper slot and equipment" /><figcaption>Additional supports defined camera distance, paper insertion and the internal equipment layout.</figcaption></figure><figure><img src="images/building progress (4).jpg" loading="lazy" alt="Animal Garden scanner with its later enclosed matte-black exterior being completed" /><figcaption>The enclosure transformed the raw frame into a durable visitor-facing exhibition object.</figcaption></figure></div>
    <h3>Testing &amp; Exhibition</h3><p>Animal Garden was repeatedly tested in its real exhibition context, where projection scale, ambient light, scanner alignment, visitor flow and long-running stability affected the final experience.</p><div class="popup-gallery popup-gallery--two"><figure><img src="images/testing the projection.jpg" loading="lazy" alt="Team members testing Animal Garden projection framing and alignment on the exhibition wall" /><figcaption>Projection tests established the scale, perspective and visual framing of the Bosch-inspired scene.</figcaption></figure><figure><img src="images/exhibit place (1).jpg" loading="lazy" alt="Animal Garden scanner, drawing table and projection installed in the Boschs Traumwelt exhibition room" /><figcaption>The completed physical-digital setup was positioned for scanner integration, calibration and visitor flow.</figcaption></figure><figure><img src="images/visitors sitting.JPG" loading="lazy" alt="Visitors seated at the Animal Garden drawing station during the public exhibition" /><figcaption>Public operation revealed how visitors understood the drawing workflow and interacted with the shared projected garden.</figcaption></figure></div>    <h3>My Contribution</h3><p>My work spanned Unity development, 2D production, environment composition, hardware prototyping, exhibition deployment and documentation. The responsibilities below are based on the internship report and distinguish my implementation work from later refinements and systems contributed by colleagues.</p>
    <h4>Unity Development</h4><ul><li>Set up the Unity development environment, created the GitHub repository and organised the project&rsquo;s folders and documentation.</li><li>Implemented the initial object-management approach, then expanded active and inactive animal tracking, on-screen limits and instance recycling as the system evolved.</li><li>Developed animal spawning, spline- and waypoint-based movement and foundational idle and movement state logic.</li><li>Built a placeholder texture-swapping simulation so animation, spawning and mapping could be tested before scanner hardware was available.</li><li>Integrated scanned-texture input, Linus Steffens&rsquo; OpenCV functionality and Ricci&rsquo;s updated animation clips into the main Unity pipeline.</li><li>Updated prefab references and file structures, tested scanned-texture compatibility, resolved minor animation-state and integration issues, and produced test builds.</li></ul>
    <h4>2D Art, Rigging &amp; Animation</h4><ul><li>Researched animal candidates in Bosch&rsquo;s painting and selected creatures according to silhouette, recognisability and animation suitability.</li><li>Created or adapted sprites, cleaned them in Photoshop and prepared all five characters for dynamic texture mapping.</li><li>Rigged all five characters with Unity 2D tools and created the initial walking and swimming animation loops.</li><li>Contributed to later animation refinement with Ricci. He improved transitions, articulation and idle quality; I integrated and tested the updated clips in the final scene.</li></ul>
    <h4>Environment &amp; Visual Composition</h4><ul><li>Isolated landscape and architectural elements from <em>The Garden of Earthly Delights</em> and removed unrelated figures, structures and background details in Photoshop.</li><li>Built the initial Unity scene, layered parallax backgrounds and environmental composition while preserving Bosch&rsquo;s visual language for projection.</li><li>Positioned assets and calibrated framing, depth and spatial composition against the exhibition surface.</li><li>Integrated animated background assets later created by Ricci; I do not claim sole authorship of the final background set.</li></ul>
    <h4>Hardware Prototyping</h4><ul><li>Planned scanner dimensions and structure collaboratively with Ricci under Michael G&ouml;dde&rsquo;s supervision.</li><li>Measured, marked and cut wooden components, assembled the structural skeleton and helped define the paper slot, camera platform and internal equipment layout.</li><li>Researched camera resolution, lens, focal distance and placement with Ricci, supporting selection of a suitable camera.</li><li>Adapted the structure when projection moved to a ceiling-mounted configuration and contributed painting, matte-black panel application and finishing.</li><li>Supported camera, PC and scanner integration, then transported and installed the completed unit in the exhibition.</li></ul>
    <h4>Exhibition Production</h4><ul><li>Supported videoreality&rsquo;s relocation to The Squaire and helped construct the wider Artworld exhibition, with direct work in the Boschs Traumwelt room.</li><li>Assisted projection, lighting and cabling setup; adjusted scene framing; and supported scanner alignment, spatial calibration and visitor-flow preparation.</li><li>Contributed to the theatrical entrance tunnel and light control, testing and calibration, ZDF filming preparations and the Artworld soft opening.</li><li>Worked directly with visitors, helped troubleshoot and maintain installations, and contributed to the exhibition staff manual.</li></ul>
    <h4>Planning &amp; Documentation</h4><ul><li>Created the early project workflow and planning document and a Gantt chart for tracking tasks and progress.</li><li>Helped define milestones, maintained development documentation and repository organisation, and supported handover and daily-operation instructions.</li></ul>
    <h3>Collaboration</h3><p>Technical Director Linus Steffens developed the core OpenCV scanning and interpretation functionality and the standardised print sheets. Riccardo Liguori contributed animation refinement, visual assets and scanner design and construction. I developed and integrated the Unity scene and interaction systems, created the initial sprites, rigs and animations, composed the environment, and contributed major parts of scanner construction and exhibition deployment. Animal Garden was completed within the wider videoreality team under internship supervisor Michael G&ouml;dde.</p>    <h3>Challenges</h3><ul><li><strong>Bridging physical and digital systems:</strong> The installation required a dependable path from printed drawing and camera capture through OpenCV alignment, Unity texture mapping, animation and projection.</li><li><strong>Preserving visitor artwork:</strong> Scanned drawings needed to remain recognisable after alignment, texture mapping, sprite deformation and movement.</li><li><strong>Continuous public operation:</strong> Active-animal management, recycling and stable builds were important as repeated visitor sessions added multiple animated creatures to the projected scene.</li><li><strong>Building for the exhibition space:</strong> Camera distance, controlled lighting, safe component placement, projection scale, glare and visitor flow required physical prototyping and repeated on-site calibration.</li></ul>
    <h3>What I Learned</h3><p>Animal Garden showed me that interactive installations require software, hardware and spatial design to be considered as one system. The placeholder texture simulation validated animation and spawning before the final scanner existed, while evolving instance management demonstrated why performance planning matters in a continuously running public experience.</p><p>Physical prototyping demanded more measurement, precision and iteration than screen-based work, and exhibition deployment introduced constraints that were not visible inside the Unity Editor. Clear documentation proved essential for handover and daily operation, while observing and supporting real visitors revealed interaction and maintenance needs that ordinary development testing could not reproduce.</p>
    <h3>Team &amp; Credits</h3><p><strong>Antonela Matanovi&#263;</strong> &mdash; Unity development and integration, initial sprites, rigs and animations, environment composition, scanner construction and exhibition support<br /><strong>Riccardo Liguori</strong> &mdash; animation refinement, visual assets and scanner collaboration<br /><strong>Linus Steffens</strong>, Technical Director &mdash; core OpenCV scanning functionality and standardised print sheets<br /><strong>Michael G&ouml;dde</strong>, Co-Founder &amp; COO &mdash; internship supervision and hardware oversight<br /><strong>videoreality GmbH</strong> &mdash; wider production and exhibition team<br />Exhibition: TimeLeapVR Artworld &ndash; Mona Lisas Geheimnis, Boschs Traumwelt, 2025</p>    <h3>Project Links</h3><div class="project-external-links"><a href="https://videoreality.de/monalisasgeheimnis" target="_blank" rel="noopener" class="project-external-link">Exhibition Website &nearr;</a></div>  `,

  insects: `
    <h2 id="popup-title">Insect&rsquo;s Delegate: Brumble&rsquo;s Journey</h2>
    <div class="popup-meta"><span>Virtual Reality</span><span>Unity</span><span>C#</span><span>Educational Experience</span><span>Interaction Design</span><span>University Team Project</span></div>
    <section class="project-quick-facts" aria-labelledby="insects-facts-title"><h3 id="insects-facts-title">Quick Facts</h3><dl class="quick-facts-grid">
      <div><dt>University</dt><dd>Darmstadt University of Applied Sciences (h_da), Germany</dd></div><div><dt>Faculty</dt><dd>Faculty of Media</dd></div><div><dt>Study Programme</dt><dd>Bachelor of Arts (B.A.) &ndash; Expanded Realities</dd></div><div><dt>Course</dt><dd>Project 3 &ndash; Discover Space and Time: Hidden Ventures Beyond the Spotlight</dd></div><div><dt>Semester</dt><dd>Winter Semester 2024</dd></div><div><dt>Project Type</dt><dd>University Team Project</dd></div><div><dt>Target Audience</dt><dd>Ages 12&ndash;16</dd></div><div><dt>Format</dt><dd>Virtual Reality Experience</dd></div><div><dt>Engine</dt><dd>Unity</dd></div><div><dt>Language</dt><dd>C#</dd></div>
    </dl></section>
    <h3>Overview</h3>
    <p><strong>Insect&rsquo;s Delegate: Brumble&rsquo;s Journey</strong> is an educational virtual reality narrative created for audiences aged 12&ndash;16. Inspired by the Senckenberg Naturmuseum Frankfurt exhibition <em>City Insects: Frankfurt&rsquo;s Tiny Helpers</em>, the experience combines storytelling, exploration and hands-on learning to introduce the ecological importance of insects without presenting itself as a museum application.</p>
    <p>The journey begins at human scale in a city park, where players discover how insect hotels can support urban habitats. A butterfly then shrinks them into a miniature world, where Brumble the bee becomes their guide through flight, climbing and pollination interactions supported by voice-acted dialogue.</p>
    <p>After learning how bees perceive flowers and completing the pollination task, the player returns to human scale. The complete arc connects practical conservation ideas with a playful perspective designed to build appreciation for pollinators and their role in healthy ecosystems.</p>
    <figure class="popup-media popup-media--contained"><img src="images/main image.png" alt="Brumble the bee flying through the colourful insect-scale flower environment in Insect&rsquo;s Delegate" /><figcaption>Brumble guides the player through the miniature pollinator world.</figcaption></figure>
    <h3>Experience Journey</h3>
    <div class="experience-journey">
      <section class="experience-stage"><p class="experience-stage-label">Stage 1</p><h4>Discovering the Hidden World</h4><p>The player explores a city park and places insect hotels inspired by the exhibition research, learning how these structures provide shelter in urban environments. Completing the task triggers a magical encounter with a butterfly, which reduces the player to insect scale and reveals the hidden world around them.</p><div class="popup-gallery popup-gallery--two"><figure><img src="images/city.png" loading="lazy" alt="Stylised city park environment at the beginning of the VR experience" /><figcaption>The opening establishes a familiar human-scale setting before the perspective changes.</figcaption></figure><figure><img src="images/insect hotel.jpg" loading="lazy" alt="Player placing an insect hotel onto a tree in the city park" /><figcaption>Placing insect hotels turns the first conservation lesson into an interactive task.</figcaption></figure></div></section>
      <section class="experience-stage"><p class="experience-stage-label">Stage 2</p><h4>Meeting Brumble</h4><p>At insect scale, the player meets Brumble and mounts the bee for a guided flight through the miniature environment. After dismounting, they climb a tree, discover a bee-inspired UV view of flowers and complete the pollination task through interactive gameplay.</p><div class="popup-gallery popup-gallery--two"><figure><img src="images/brumble.png" loading="lazy" alt="Brumble the bee surrounded by oversized colourful flowers" /><figcaption>Brumble provides a friendly narrative guide through the insect-scale world.</figcaption></figure><figure><img src="images/riding brumble.jpg" loading="lazy" alt="First-person view of the player riding Brumble through the flower environment" /><figcaption>The mounted flight links guided movement with environmental storytelling.</figcaption></figure><figure><img src="images/environment.png" loading="lazy" alt="Oversized flower and plant environment viewed from an insect-scale perspective" /><figcaption>Large plants and dense foliage make the player&rsquo;s reduced scale immediately legible.</figcaption></figure><figure><img src="images/climbing the tree.jpg" loading="lazy" alt="First-person view of the player climbing the bark of a tree after dismounting" /><figcaption>Climbing shifts the journey from guided travel back to direct physical interaction.</figcaption></figure><figure><img src="images/tree ladder.jpg" loading="lazy" alt="Ladder-like route leading upward through the tree in the miniature environment" /><figcaption>The tree route structures navigation towards the pollination sequence.</figcaption></figure><figure><img src="images/flowers.png" loading="lazy" alt="Dense colourful flowers in the miniature environment before the pollination task" /><figcaption>The flower landscape establishes the setting and targets for the final gameplay task.</figcaption></figure><figure><img src="images/pollination.jpg" loading="lazy" alt="Flower highlighted through the bee-inspired UV visualisation during pollination" /><figcaption>Bee-inspired vision helps the player identify flower patterns relevant to pollination.</figcaption></figure></div></section>
      <section class="experience-stage"><p class="experience-stage-label">Stage 3</p><h4>Returning Home</h4><p>Once the pollination task is complete, the butterfly restores the player to human scale. Returning to the city park closes the narrative loop and reinforces how pollinators support ecosystems, encouraging players to view insects and urban conservation with greater appreciation.</p></section>
    </div>
    <h3>Video</h3><div class="video-container"><iframe src="https://www.youtube.com/embed/hUOfJCqo2rE" title="Insect’s Delegate: Brumble’s Journey project trailer" allowfullscreen></iframe></div>
    <h3>Technical Highlights</h3>
    <p>The experience was developed in Unity and C# with the XR Interaction Toolkit. VR locomotion and interaction systems support movement at human and insect scale, direct environmental interaction, hand animation and transitions between guided and player-controlled sequences.</p>
    <ul><li><strong>Mounted movement:</strong> A player-mounting system, bee movement logic and coroutine-based follow behaviour synchronise the player with Brumble during flight and return control after dismounting.</li><li><strong>Experience flow:</strong> Scene management, environmental triggers and state progression connect insect-hotel placement, the shrinking transition, guided flight, tree climbing, UV-inspired bee vision and pollination.</li><li><strong>Navigation and iteration:</strong> NavMesh debugging supported Brumble&rsquo;s movement, while rapid prototypes and user testing informed interaction comfort, clarity and polish.</li><li><strong>Visual development:</strong> Blender supported environmental prop production, alongside Unity shader experimentation for the insect-scale world and bee-inspired flower visualisation.</li><li><strong>Production workflow:</strong> Jira was used for task organisation, milestone planning and coordination across design, development, documentation and testing.</li></ul>
    <h3>My Contribution</h3>
    <p>I contributed across experience design, technical development, environment design and production. The final experience was a collaborative team achievement; the responsibilities below describe my documented individual work within that shared production.</p>
    <h4>Experience Design</h4><ul><li>Researched the museum exhibition and analysed its themes through design-thinking and semantic-analysis methods.</li><li>Contributed to the educational concept, personas and complete user journey.</li><li>Developed story material, dialogue and gameplay-flow planning connecting conservation learning with interactive tasks.</li></ul>
    <h4>Technical Development</h4><ul><li>Developed VR functionality in Unity and C# using the XR Interaction Toolkit, including locomotion and hand-animation integration.</li><li>Implemented and refined the bee-riding and player-mounting flow, movement synchronisation and coroutine-based follow behaviour.</li><li>Prototyped the shrinking transition and contributed scene-management and interaction logic.</li><li>Debugged NavMesh behaviour and Brumble&rsquo;s movement, then polished interactions through iteration and testing.</li></ul>
    <h4>Environment Design</h4><ul><li>Created the human-scale city-park blockout and contributed to level-layout planning.</li><li>Modelled environmental props including benches, street lamps, park signs and rubbish bins.</li><li>Explored shader approaches supporting the project&rsquo;s visual and interaction goals.</li></ul>
    <h4>Production</h4><ul><li>Set up Jira and supported task organisation, production planning and milestone presentations.</li><li>Contributed project documentation and coordinated the team&rsquo;s Medium development-blog workflow.</li></ul>
    <h3>Challenges</h3>
    <p>The central production challenge was shaping educational material into gameplay that remained engaging for a young audience. The team had to balance a clear narrative with player agency, combine several interaction modes into one understandable flow and maintain comfortable locomotion while moving between human scale, mounted flight and direct climbing.</p>
    <p>Interdisciplinary collaboration required design, writing, environment work and programming to evolve together rather than as isolated tasks. Rapid prototypes and user testing exposed assumptions about comfort and interaction clarity, making iteration and production coordination essential to the final experience.</p>
    <h3>What I Learned</h3>
    <p>This project reinforced that educational VR works best when learning is embedded in intuitive actions rather than separated into explanation. Prototyping core transitions and movement early made it easier to evaluate the experience as a complete journey, while user testing provided evidence that challenged design assumptions and directed interaction polish.</p>
    <p>I also learned that production planning is as important as implementation in an interdisciplinary XR project. Clear task ownership, milestones and documentation helped the team connect narrative, visual design, programming and educational goals into a more coherent result.</p>
    <h3>Team</h3><p>Jacopo Perilli &middot; Lara He&szlig; &middot; Mutlu Yakubov &middot; Antonela Matanovi&#263; &middot; Himanshu Dahiya</p>
    <h3>Project Links</h3><div class="project-external-links"><a href="https://www.youtube.com/watch?v=hUOfJCqo2rE" target="_blank" rel="noopener" class="project-external-link">Watch Project Video &nearr;</a><a href="https://museumfrankfurt.senckenberg.de/en/" target="_blank" rel="noopener" class="project-external-link" aria-label="Exhibition Inspiration: Senckenberg Naturmuseum Frankfurt">Senckenberg Naturmuseum Frankfurt &nearr;</a></div>  `
};

let lastFocusedElement = null;

function openPopup(projectKey) {
  const content = projectsData[projectKey];
  if (!content) return;
  lastFocusedElement = document.activeElement;
  popupContent.innerHTML = content;
  popup.classList.add("active");
  popup.setAttribute("aria-hidden", "false");
  document.body.classList.add("no-scroll");
  const popupTitle = popupContent.querySelector("#popup-title");
  if (popupTitle) {
    popupTitle.setAttribute("tabindex", "-1");
    setTimeout(() => popupTitle.focus(), 80);
  }
}

function closePopup() {
  popup.classList.remove("active");
  popup.setAttribute("aria-hidden", "true");
  document.body.classList.remove("no-scroll");
  setTimeout(() => {
    popupContent.innerHTML = "";
    if (lastFocusedElement) lastFocusedElement.focus();
  }, 180);
}

const categoryButtons = document.querySelectorAll(".project-category-button");
const projectRows = document.querySelectorAll(".project-row[data-category]");
const projectEmptyState = document.getElementById("project-empty-state");

function filterProjects(category) {
  categoryButtons.forEach((button) => {
    const isActive = button.dataset.categoryFilter === category;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  let visibleProjects = 0;
  projectRows.forEach((row) => {
    const isVisible = row.dataset.category === category;
    row.classList.toggle("project-row--hidden", !isVisible);
    row.setAttribute("aria-hidden", String(!isVisible));
    if (isVisible) visibleProjects += 1;
  });

  projectEmptyState.hidden = visibleProjects > 0;
}

categoryButtons.forEach((button) => {
  button.addEventListener("click", () => filterProjects(button.dataset.categoryFilter));
});

filterProjects("university");
document.querySelectorAll(".project-link").forEach((button) => {
  button.addEventListener("click", () => openPopup(button.dataset.project));
});

closeBtn.addEventListener("click", closePopup);

popup.addEventListener("click", (event) => {
  if (event.target === popup) closePopup();
});

document.addEventListener("keydown", (event) => {
  if (event.key === "Escape" && popup.classList.contains("active")) closePopup();
});

navMenuButton.addEventListener("click", () => {
  const isOpen = navList.classList.toggle("open");
  navMenuButton.setAttribute("aria-expanded", String(isOpen));
});

document.querySelectorAll(".nav-link").forEach((link) => {
  link.addEventListener("click", () => {
    navList.classList.remove("open");
    navMenuButton.setAttribute("aria-expanded", "false");
  });
});

function updateScrollProgress() {
  const scrollTop = window.scrollY;
  const scrollableHeight = document.documentElement.scrollHeight - window.innerHeight;
  const progress = scrollableHeight > 0 ? (scrollTop / scrollableHeight) * 100 : 0;
  scrollProgress.style.width = `${progress}%`;
}

window.addEventListener("scroll", updateScrollProgress, { passive: true });
window.addEventListener("resize", updateScrollProgress);
updateScrollProgress();